[config]
default_to_workspace = false

[tasks.firmware]
command = "cargo"
args = ["build", "-p=at28c-rs-firmware", "--release", "--target=thumbv7m-none-eabi"]

[tasks.size]
script = [
    "cd at28c-rs-firmware",
    "cargo size --bin=at28c-rs-firmware --release --target=thumbv7m-none-eabi",
]
dependencies = ["firmware"]

[tasks.sizea]
script = [
    "cd at28c-rs-firmware",
    "cargo size --bin=at28c-rs-firmware --release --target=thumbv7m-none-eabi -- -A",
]
dependencies = ["firmware"]

[tasks.cli]
command = "cargo"
args = ["build", "-p=at28c-rs-cli", "--release"]

[tasks.cli-debug]
command = "cargo"
args = ["build", "-p=at28c-rs-cli"]

[tasks.all]
dependencies = [
    "firmware",
    "cli",
]

[tasks.gdb]
command = "cargo"
args = ["run", "-p=at28c-rs-firmware", "--release", "--target=thumbv7m-none-eabi"]

[tasks.flash]
script = [
    "cd at28c-rs-firmware",
    "cargo flash --release --target=thumbv7m-none-eabi --chip stm32f103c8",
]
dependencies = ["firmware"]

#[tasks.flash]
#script = [
#    "openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg -c \"program target/thumbv7m-none-eabi/release/at28c-rs-firmware verify reset exit\""
#]
#dependencies = ["firmware"]
